name: Impulse Scanner Alerts

on:
  schedule:
    # runs at 06:30 UTC => 08:30 SAST (London pre-open)
    - cron: '30 6 * * 1-5'
    # runs at 12:00 UTC => 14:00 SAST (NY pre-open / as requested)
    - cron: '0 12 * * 1-5'
  workflow_dispatch: {}

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance python-telegram-bot pandas pytz

      - name: Run impulse scanner
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python impulse_scanner.py
