name: Impulse Scanner Alerts

on:
  schedule:
    - cron: '30 6 * * 1-5'  # 08:30 SAST (London pre-open)
    - cron: '0 13 * * 1-5'  # 30 min before NY open (summer time)
  workflow_dispatch: {}

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance python-telegram-bot pytz
      - name: Run impulse scanner
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}
        run: python impulse_scanner.py
